# Use a base image of Ubuntu 20.04
FROM ubuntu:20.04

# Update package list and install Java 17 and Maven
RUN apt-get update && apt-get install -y openjdk-17-jdk maven
RUN apt install git -y

# Clone the GitHub repository (optional if you have the source code locally)
RUN git clone https://github.com/Alfesito/ISST-Grupo13-NutriApp.git

# Set the working directory to the cloned repository
WORKDIR /ISST-Grupo13-NutriApp

# Copy the source code into the Docker image
# COPY . .

# Create a volume for the data directory
VOLUME /data

# Copy the entrypoint script
COPY entrypoint.sh /

# Make the entrypoint script executable
RUN chmod +x /entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/entrypoint.sh"]

# Expose port 8080 (change the number if your application uses a different port)
EXPOSE 8080

# Pasos para contruir la imagen un ejecutar el contenedor:
#     $ docker build -t nutri-app .
#     $ docker run -p 8080:8080 nutri-app

# Eliminar la imagen(es importante eliminar todos los contenedores creados, de otra forma puede que de problemas):
#     $ docker rmi -f nutri-app