# Definir el servicio
  # $ kubectl apply -f nutri-app.yaml
  # $ minikube service nutri-app --url
# ELiminar el servicio
  # $ kubectl delete -f nutri-app.yaml
  # $ kubectl delete service nutri-app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutri-app
  labels:
    app: nutri-app
    service: nutri-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nutri-app
  template:
    metadata:
      labels:
        app: nutri-app
    spec:
      containers:
        - name: nutri-app
          image: equipo32/nutri-app:latest # utiliza la misma imagen base que el Dockerfile
          ports:
            - containerPort: 443 # expone el puerto 443
---
apiVersion: v1
kind: Service
metadata:
  name: nutri-app
  labels:
    app: nutri-app
    service: nutri-app
spec:
  selector:
    app: nutri-app
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 443
